baseURL = "http://example.org/"
languageCode = "en-us"
title = "feministclickback.org"
disableKinds = ["taxonomy", "taxonomyTerm"]
sectionPagesMenu = "headerMenu"
[markup.goldmark.renderer]
unsafe= true
